spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb+srv://admin:admin@testclustor.1wxlq0q.mongodb.net/treaty?retryWrites=true&w=majority
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration